### ISSUE TITLE
Delete internal flavors

### ISSUE THREAD

**Issue by berendt** [osism/python-osism#116]
The internal flavors of a baremetal node must be deleted when a node is deleted.

**Comment by berendt** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/osism/tasks/openstack.py", line 219, in baremetal_delete_internal_flavor
    conn.compute.delete_flavor(name=f"osism-{node}")
TypeError: Proxy.delete_flavor() got an unexpected keyword argument 'name'
```
